### ISSUE TITLE
CIC BC: Followup PROMS: Missing question  ( precondition issue)

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1427]
In the CIC BC Followup PROMS surveys, on desktop Chrome or Google Chrome for Android One.

The question `SYSTDATEPATIENT` ("If the systemic treatment has stopped, when did you stop your treatment?") after `SYSTPATIENT` ("In the past year have you received systemic (ie drug) treatment for breast cancer?") is not asked regardless of the answer(s) to the prior question.

May be related to #1426, as the same display error occurs for `SYSTPATIENT`.

**Comment by id2359** [comment]
Looks like precondition not satisfied SYSTPATIENT

Check the expression

**Comment by id2359** [comment]
The precondition is not being satisfied because checked value is a multiselect 
The default check is equality 

( We currently support:

value equals check value
e.g.  "2" equals "2"

value in checked value
where checked value is a comma-separated list as : 1,2,3
but this is implicit behaviour 

In this case a multiselect is providing the answer and the checked value has been set to "1"
if the selected value is "1" the precondition holds

this will never be true because even if a single value ( say 1) is selected , the answer will be ["1"] not "1"

what is needed is an explicit operator "contains"

value contains check_value
