### ISSUE TITLE
OVMOST: Followup survey errors

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1510]
In the OVMOST Six Months survey, desktop Google Chrome browser, responsive design (iphone x).

The order of questions is somewhat odd;
- Question 22 follows question 1. Question 2 then follows question 22.
- Question 55 follows question 4. Question 5 then follows question 55.
- Pain/Discomfort is skipped near the end, and is asked after YOUR HEALTH TODAY.
  - Pain/Discomfort is now the final question.

**Comment by id2359** [comment]
Numbers are in the "name" of the cdes ( labels)


survey questions in smap:

position cde code  [cde name]
2 MOSTv21_Q2 [2: Abdominal swelling, bloating and/or feelings of fullness]
3 MOSTv21_Q3 [3: Indigestion]
26 CANHELP_Lite_Q5 [26: How satisfied are you that the doctors, nurses, and other health care professionals who looked after you knew enough about your health problems to give you the best possible care?]
27 CANHELP_Lite_Q7 [27: How satisfied are you that physical symptoms you had (for example: pain, shortness of breath, nausea) were adequately assessed and controlled?]
28 CANHELP_Lite_Q8 [28: How satisfied are you that emotional problems you had (for example: depression, anxiety) were adequately assessed and controlled?]
29 CANHELP_Lite_Q14 [29: How satisfied are you that the doctor(s) explained things relating to your illness in a straight-forward, honest manner?]
30 CANHELP_Lite_Q15 [30: How satisfied are you that you received consistent information about your condition from all doctors and nurses looking after you?]
31 CANHELP_Lite_Q16 [31: How satisfied are you that the doctor(s) listened to what you had to say?]
113 EQ_Anxiety_Depress [ANXIETY / DEPRESSION]
115 EQ_Pain_Discomfort [PAIN / DISCOMFORT]
4 MOSTv21_Q4 [4: Difficulties eating]
25 MOSTv21_Q25 [25: Depression (feeling sad)]
46 EORTCQLQC30_Q15 [46: Have you vomited?]
47 EORTCQLQC30_Q16 [47: Have you been constipated?]
48 EORTCQLQC30_Q17 [48: Have you had diarrhoea?]
49 EORTCQLQC30_Q18 [49: Were you tired?]
50 EORTCQLQC30_Q19 [50: Did pain interfere with your daily activities?]
51 EORTCQLQC30_Q20 [51: Have you had difficulty in concentrating on things, like reading a newspaper or watching television?]
52 EORTCQLQC30_Q21 [52: Did you feel tense?]
53 EORTCQLQC30_Q22 [53: Did you worry?]
54 EORTCQLQC30_Q23 [54: Did you feel irritable?]
5 EORTCQLQC30_Q24 [55: Did you feel depressed?]
56 EORTCQLQC30_Q25 [56: Have you had difficulty remembering things?]
57 EORTCQLQC30_Q26 [57: Has your physical condition or medical treatment interfered with your family life?]
114 EQ_Health_Rate [YOUR HEALTH TODAY]
58 EORTCQLQC30_Q27 [58: Has your physical condition or medical treatment interfered with your social activities?]
59 EORTCQLQC30_Q28 [59: Has your physical condition or medical treatment caused you financial difficulties?]
60 EORTCQLQC30_Q29 [60: How would you rate your overall health during the past week?]
61 EORTCQLQC30_Q30 [61: How would you rate your overall quality of life during the past week?]
110 EQ_Mobility [MOBILITY]
111 EQ_Selfcare [PERSONAL CARE]
112 EQ_UsualActivities [USUAL ACTIVITIES]
62 FACT_O_Q1 [62: I have a lack of energy]
63 FACT_O_Q2 [63: I have nausea]
64 FACT_O_Q3 [64: Because of my physical condition, I have trouble meeting the needs of my family]
65 FACT_O_Q4 [65: I have pain]
66 FACT_O_Q5 [66: I am bothered by side effects of treatment]
67 FACT_O_Q6 [67: I feel ill]
68 FACT_O_Q7 [68: I am forced to spend time in bed]
69 FACT_O_Q8 [69: I feel close to my friends]
70 FACT_O_Q9 [70: I get emotional support from my family]
71 FACT_O_Q10 [71: I get support from my friends]
72 FACT_O_Q11 [72: My family has accepted my illness]
73 FACT_O_Q12 [73: I am satisfied with family communication about my illness]
74 FACT_O_Q13 [74: I feel close to my partner (or the person who is my main support)]
75 FACT_O_Q14 [75: I am satisfied with my sex life]
76 FACT_O_Q15 [76: I feel sad]
77 FACT_O_Q16 [77: I am satisfied with how I am coping with my illness]
78 FACT_O_Q17 [78: I am losing hope in the fight against my illness]
79 FACT_O_Q18 [79: I feel nervous]
80 FACT_O_Q19 [80: I worry about dying]
81 FACT_O_Q20 [81: I worry that my condition will get worse]
82 FACT_O_Q21 [82: I am able to work (include work at home)]
83 FACT_O_Q22 [83: My work (include work at home) is fulfilling]
84 FACT_O_Q23 [84: I am able to enjoy life]
85 FACT_O_Q24 [85: I have accepted my illness]
86 FACT_O_Q25 [86: I am sleeping well]
87 FACT_O_Q26 [87: I am enjoying the things I usually do for fun]
88 FACT_O_Q27 [88: I am content with the quality of my life right now]
89 FACT_O_Q28 [89: I have swelling in my stomach area]
90 FACT_O_Q29 [90: I am losing weight]
91 FACT_O_Q30 [91: I have control of my bowels]
92 FACT_O_Q31 [92: I have been vomiting]
93 FACT_O_Q32 [93: I am bothered by hair loss]
94 FACT_O_Q33 [94: I have a good appetite]
95 FACT_O_Q34 [95: I like the appearance of my body]
96 FACT_O_Q35 [96: I am able to get around by myself]
1 MOSTv21_Q1 [1: Abdominal pains, discomfort and/or cramps]
32 EORTCQLQC30_Q01 [32: Do you have any trouble doing strenuous activities, like carrying a heavy shopping bag or a suitcase?]
33 EORTCQLQC30_Q02 [33. Do you have any trouble taking a long walk?]
34 EORTCQLQC30_Q03 [34: Do you have any trouble taking a short walk outside of the house?]
35 EORTCQLQC30_Q04 [35: Do you need to stay in bed or a chair during the day?]
36 EORTCQLQC30_Q05 [36: Do you need help with eating, dressing, washing yourself or using the toilet?]
37 EORTCQLQC30_Q06 [37: Were you limited in doing either your work or other daily activities?]
38 EORTCQLQC30_Q07 [38: Were you limited in pursuing your hobbies or other leisure time activities?]
39 EORTCQLQC30_Q08 [39: Were you short of breath?]
40 EORTCQLQC30_Q09 [40: Have you had pain?]
41 EORTCQLQC30_Q10 [41: Did you need to rest?]
42 EORTCQLQC30_Q11 [42: Have you had trouble sleeping?]
43 EORTCQLQC30_Q12 [43: Have you felt weak?]
44 EORTCQLQC30_Q13 [44: Have you lacked appetite?]
45 EORTCQLQC30_Q14 [45: Have you felt nauseated?]
97 FACT_O_Q36 [97: I am able to feel like a woman]
98 FACT_O_Q37 [98: I have cramps in my stomach area]
99 FACT_O_Q38 [99: I am interested in sex]
100 FACT_O_Q39 [100: I have concerns about my ability to have children]
101 FRCI_V2_Q1 [101: I am worried or anxious about the possibility of cancer recurrence]
102 FRCI_V2_Q2 [102:  I am afraid of cancer recurrence]
103 FRCI_V2_Q3 [103:  I believe it is normal to be worried or anxious about the possibility of cancer recurrence]
104 FRCI_V2_Q4 [104:  When I think about the possibility of cancer recurrence, this triggers other unpleasant thoughts or images (such as death, suffering, the consequences for my family)]
105 FRCI_V2_Q5 [105:  I believe that I am cured and that the cancer will not come back]
106 FRCI_V2_Q6 [106:  In your opinion, are you at risk of having a cancer recurrence?]
107 FRCI_V2_Q7 [107:  How often do you think about the possibility of cancer recurrence?]
108 FRCI_V2_Q8 [108:  How much time per day do you spend thinking about the possibility of cancer recurrence?]
109 FRCI_V2_Q9 [109:  How long have you been thinking about the possibility of cancer recurrence?]
5 MOSTv21_Q5 [5: Difficulties swallowing]
6 MOSTv21_Q6 [6: Diarrhoea]
7 MOSTv21_Q7 [7: Constipation]
8 MOSTv21_Q8 [8: Shortness of breath]
9 MOSTv21_Q9 [9: Nausea]
10 MOSTv21_Q10 [10: Vomiting]
11 MOSTv21_Q11 [11: Sleeping problems]
12 MOSTv21_Q12 [12: Tiredness]
13 MOSTv21_Q13 [13: Bladder problems]
14 MOSTv21_Q14 [14: Physical wellbeing]
15 MOSTv21_Q15 [15: Emotional wellbeing]
16 MOSTv21_Q16 [16: General wellbeing]
17 MOSTv21_Q17 [17: Change in ability to taste]
18 MOSTv21_Q18 [18: Soreness in the mouth or sore throat]
19 MOSTv21_Q19 [19: Hair loss]
20 MOSTv21_Q20 [20: Skin breakouts / rash]
21 MOSTv21_Q21 [21: Numbness or tingling]
2 MOSTv21_Q22 [22: Pains in the hands and feet]
23 MOSTv21_Q23 [23: Trouble concentrating]
24 MOSTv21_Q24 [24: Anxiety (being worried)]

**Comment by id2359** [comment]
need to confirm ordering of survey questions

why numbers added to labels/name in the cde

**Comment by id2359** [comment]
Question ordering OKed by Angela Ives
