### ISSUE TITLE
CIC CRC: Deidentified Report - columns not grouped

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1571]
In CIC CRC v1.29 (RDRF v6.2.0).
When viewing data in the CSV-converted Deidentified Report, the columns for specific forms are not grouped together in some cases. For example, for `FollowUpProms/2`, the data for each patient are contained in columns SL-VD, BBS-BBZ, BJG, BJH, and BUQ-BVS of the CSV. For `FollowUpProms/3`, the data are contained in columns B-BT, WI-WP, and BVT-BVV.

**Comment by jithendralal** [comment]
The new columns are being added to the pandas data frame as they are found in the de-identified report
while iterating through the patients' contexts ordered by context_id.

TO FIX this issue of columns getting scattered, the new column can be inserted (to keep them grouped together) instead of appending the new columns to the data frame.

**Comment by jithendralal** [comment]
The fix was committed to the same branch cicap#1

**Comment by jithendralal** [comment]
The new csv generated after making changes is attached:
[staging-crc_20200917122654.txt](https://github.com/muccg/rdrf/files/5303405/staging-crc_20200917122654.txt)

Please test this csv.
