### ISSUE TITLE
Failed to load source map on FH when control shift J pressed

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1790]
- [x] Can we avoid this - it looks to the enduser like an error.
- [ ] It might aid in debugging if we got it working

**Comment by APMCCG** [comment]
The "DevTools failed to load SourceMap" warning is caused by Google Chrome automatically enabling source map support, and can be disabled in the Chrome developer tools settings. The file Chrome is attempting to load (https://rdrf.ccgapps.com.au/ophg/static/js/vendor/underscore-min.map) does not exist in RDRF. Warning does not appear in Firefox. More details at https://stackoverflow.com/questions/61339968/devtools-failed-to-load-sourcemap-could-not-load-content-for-chrome-extension.
