### ISSUE TITLE
CSP: Bootstrap SVGs not displaying

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1857]
This ticket relates to #1801.
Bootstrap loads SVGs using URLs (e.g. ""data:image/svg+xml,\<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='#{$carousel-control-color}'>\<path d='M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z'/>\</svg>"), which are blocked by the CSP. A possible solution for this is to add the image URLs to the CSP header.

**Comment by jithendralal** [comment]
1. Home page shows this error in console:

Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300italic,300,400italic,500,500italic,700,700italic,900,900italic' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-hashes' 'sha256-aqNNdDLnnrDOnTNdkJpYlAxKVJtLt9CtFLklmInuUAE='". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

2. /static/css/compiled/theme.css has this reference:
@import url(../../bootstrap-3.3.6/css/bootstrap.min.css);
