### ISSUE TITLE
populate redis blackboard with metadata describing instance

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1940]
for cicmr
Need dictionary per registry container  in redis like:

ichomcrc-config:   {  "api-url" : "https://<containername>/etc", "api-token" : xyz }

needs to be populated  when requests/a19 queries are made 
also api setup once when container starts up (once)

**Comment by id2359** [comment]
Looks like we can put code in the app config block to run once only on app load

**Comment by jithendralal** [comment]
- apps.py cannot get "registry_code" initially
- since rdrf supports multiple registries, keeping a registry_code in the env is against the design
- patient query is supposed to add the umrn to the umrns set in the registry config
- so instead of doing the initial populating of the registry config in redis on starting of the container, it can be done as part of patient query
