### ISSUE TITLE
Cleanup of  HL7 messages in redis

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1991]
Not sure what to do here but redis will fill up over time

**Comment by jithendralal** [comment]
The FAQ in documentation says:
Tasks are acknowledged (removed from the queue) as soon as they’re actually executed. After the worker has received a task, it will take some time until it’s actually executed, especially if there are a lot of tasks already waiting for execution. Messages that aren’t acknowledged are held on to by the worker until it closes the connection to the broker. When that connection is closed (e.g., because the worker was stopped) the tasks will be re-sent by the broker to the next available worker (or the same worker when it has been restarted), so to properly purge the queue of waiting tasks you have to stop all the workers, and then purge the tasks using celery.control.purge().

https://docs.celeryproject.org/en/stable/faq.html#id24
