### ISSUE TITLE
Screenshots of slider controls used in CIC/Proms

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#743]
Include information ( text) as comment to this ticket detailing exact behaviour of the control.

**Comment by aminur80** [comment]
_Figure: Initial State_
![initial_health_rating](https://user-images.githubusercontent.com/24203846/51582926-29ebd980-1f09-11e9-8168-8c909b4c2e3b.png)
_Figure: value selected_
![value_select_01](https://user-images.githubusercontent.com/24203846/51582937-32dcab00-1f09-11e9-80e1-4d46a57b3ae1.png)
_Figure: value selected_
![value_selected_02](https://user-images.githubusercontent.com/24203846/51582943-36703200-1f09-11e9-9d09-0fd1453ec777.png)
_Figure: Step size 0.25_
![step_size_0 25](https://user-images.githubusercontent.com/24203846/51582945-3a03b900-1f09-11e9-813e-d1e21dda646c.png)

API Name: rc-slider
Slider UI Component for React
Supports IE9, IE9+, Chrome, Firefox & Safari

Some of the key properties:

| name  | type | default | description |
| ------------- | ------------- |-------------|------------|
| min | number |	0 | the minimum value of the slider |
| max | number | 100 | the maximum value of the slider |
| marks | object{number:	string} or object {number:{ style, label }}	| {} |	Mark on the slider. The key determines the position, and the value determines what will show. If you want to set the style of a specific mark point, the value should be an object which contains `style` and `label` properties.|
| step | number or null | 1 | Value to be added or subtracted on each step the slider makes. Must be greater than zero. max - min should be evenly divisible by the step value. support decimal value |
| range | boolean | false | Determines the type of slider. If range is `true`, two handles will be rendered in order to select a range.|
| vertical |	boolean | false	| If vertical is `true`, the slider will be vertical. |
| value | number or	[number, number]	|  | set current positions of handles. If range is`false`, the type of `defaultValue` should be `number`. Otherwise, `[number, number]`|
| dot | boolean | false | When the step value is greater than 1, you can set the dots to true if you want to render the slider with dots.|

**Comment by aminur80** [comment]
Link - https://www.npmjs.com/package/rc-slider

**Comment by aminur80** [comment]
[rc-slider.docx](https://github.com/muccg/rdrf/files/2785937/rc-slider.docx)

**Comment by aminur80** [comment]
What is achievable:
To make the slider look and feel like EQ5D, we can mark the slider with values which is configurable (within
the code) and therefore the slider can have marks 0, 10, 20, 30, 40 and so on.
Here is a screen shot -

![slider_with_marks](https://user-images.githubusercontent.com/24203846/51593679-b60ff800-1f2d-11e9-9c30-5c6139f072d4.png)
