### ISSUE TITLE
Survey request emails must be handled by RDRF notification

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#902]
Email received when sending POEM PROMS survey displays text for CIC CRC PROMS survey. The first line is; “You are receiving this email because you agreed to take part in the Continuous Improvement in Care – Cancer Project.”
[Test result in Google Drive.](https://drive.google.com/open?id=1WtLajhV2Q5fI7uPBeKGZMYqf8NTl2h-V)

**Comment by mouneyrac** [comment]
check email template object (email notification)

**Comment by mouneyrac** [comment]
This is what we want to create as template for CIC:
subject: {{registry_name}} {{survey_name}} Survey Request
topic: Hello {{display_name}}<br>
<br>
You are receiving this email because you agreed to take part in the Continuous Improvement in Care - Cancer Project.<br>
<br>
We would appreciate if you could complete the following survey prior to your next appointment with the doctor.<br>
<br>
Your answers will help your doctor to identify any areas where you are having problems, so that these can be addressed promptly.<br>
<br>
Please click on the following link to begin the survey:<br>
<br>
{{email_link}}

**Comment by mouneyrac** [comment]
We need to provide the subject/topic for POEM too (and angelman probably) before testing this issue once merged. Obviously these notification template need to be set on each staging site and use by a notification Survey Request type.

**Comment by gmaloneccg** [comment]
Failed 20190902 11:54am. Emails not received when sent, for patients in both POEM and CIC. In admin page for CIC, options relating to emails return an empty list.
[Example: Email Templates](https://rdrf.ccgapps.com.au/cicclinical/admin/rdrf/emailtemplate/)
![Empty list for Email Templates](https://user-images.githubusercontent.com/50615516/64089492-df70ec00-cd78-11e9-8238-28e8bcca59ed.png)

**Comment by gmaloneccg** [comment]
Tested for CIC, passed 20190902 12:12pm. Followup PROMS survey received and completed, and pulled correctly. [Test result in Drive.](https://drive.google.com/open?id=1RccSihpYm9ugsrFs55ptC7ScHk85XoKY)
