### ISSUE TITLE
Possible redundant repeat question in FollowUpPROMS survey

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#913]
Questionnaire position 71 has CDE EORTCQLQC29_Q58, which is not in the survey default form. This question does not appear in the survey/questionnaire, and may be redundant. The question is also a repeat of an earlier question, but with a precondition, meaning that women are asked this question twice in near succession. 

[FollowUpPROMS survey edit page.](https://rdrf.ccgapps.com.au/cicclinical/admin/rdrf/survey/26/change/)

Causes validation error when attempting to save FollowUpPROMS survey edit page, but this is correct (no issue).

**Comment by mouneyrac** [comment]
It looks to me like a survey design problem? Not related to the RDRF framework?

**Comment by mouneyrac** [comment]
I think Angela said she will look at confirming if it is a problem because she was not aware of a form having twice the same questions display to the user. Leaving this issue open till we confirm if there is a problem and who needs to deal with it (.i.e. is it some problem linked to the code or the designer actions)
